import {LibraryItem} from '../interfaces/library-item.interface';
import {MediaType} from '../enums/media-type.enum';

export const LIBRARY_ITEMS: LibraryItem[] = [
  {
    id: 1,
    mediaType: MediaType.Film,
    title: "Pulp Fiction",
    release_date: "1994-1-1",
    starring: ["John Travolta", "Uma Thurman"],
    directors: ["Quentin Tarantino"],
    poster_path: "assets/posters/1.jpg",
    vote_average: 9.2,
    genres: [],
    credits: {
      id: 1,
      cast: [],
      crew: []
    }
  },
  {
    id: 2,
    mediaType: MediaType.Film,
    title: "Prisoners",
    release_date: "2013-1-1",
    starring: ["Hugh Jackman", "Jake Gyllenhaal"],
    directors: ["Denis Villeneuve"],
    poster_path: "assets/posters/2.jpg",
    vote_average: 9.1,
    genres: [],
    credits: {
      id: 2,
      cast: [],
      crew: []
    }
  },
  {
    id: 3,
    mediaType: MediaType.Film,
    title: "The Blues Brothers",
    release_date: "1980-1-1",
    starring: ["John Belushi", "Dan Aykroyd"],
    directors: ["John Landis"],
    poster_path: "assets/posters/3.jpg",
    vote_average: 8.8,
    genres: [],
    credits: {
      id: 3,
      cast: [],
      crew: []
    }
  },
  // {
  //   id: 4,
  //   mediaType: MediaType.Film,
  //   title: "Inception",
  //   release_date: "2010-1-1",
  //   genres: [28, 12],
  //   starring: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
  //   directors: ["Christopher Nolan"],
  //   poster_path: "assets/posters/4.jpg",
  //   vote_average: 9,
  // },
  // {
  //   id: 5,
  //   mediaType: MediaType.Film,
  //   title: "The Godfather",
  //   release_date: "1972-1-1",
  //   overview:
  //     "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
  //   genres: [80, 18],
  //   starring: ["Marlon Brando", "Al Pacino"],
  //   directors: ["Francis Ford Coppola"],
  //   poster_path: "assets/posters/9.jpg",
  //   vote_average: 9.1,
  // },
  // {
  //   id: 6,
  //   mediaType: MediaType.Film,
  //   title: "The Matrix",
  //   release_date: "1999-1-1",
  //   genres: [28, 878],
  //   starring: ["Keanu Reeves", "Laurence Fishburne"],
  //   directors: ["Lana Wachowski", "Lilly Wachowski"],
  //   poster_path: "assets/posters/10.jpg",
  //   vote_average: 9.2,
  // },
  // {
  //   id: 7,
  //   mediaType: MediaType.Film,
  //   title: "Dune Part Two",
  //   release_date: "2024-1-1",
  //   genres: [28, 878],
  //   starring: ["Timothée Chalamet", "Zendaya"],
  //   directors: ["Denis Villeneuve"],
  //   poster_path: "assets/posters/11.jpg",
  //   vote_average: 9.1,
  // },
  // {
  //   id: 8,
  //   mediaType: MediaType.Film,
  //   title: "Alien",
  //   release_date: "1979-1-1",
  //   genres: [878, 27],
  //   starring: ["Sigourney Weaver", "gourney Weaver"],
  //   directors: ["Ridley Scott"],
  //   poster_path: "assets/posters/12.jpg",
  //   vote_average: 8.8,
  // },
  // {
  //   id: 9,
  //   mediaType: MediaType.Film,
  //   title: "Memento",
  //   release_date: "2000-1-1",
  //   genres: [53],
  //   starring: ["Guy Pearce", "Carrie-Anne Moss"],
  //   directors: ["Christopher Nolan"],
  //   poster_path: "assets/posters/13.jpg",
  //   vote_average: 9.2,
  // },
  // {
  //   id: 10,
  //   mediaType: MediaType.Film,
  //   title: "Raiders of The Lost Ark",
  //   release_date: "1981-1-1",
  //   genres: [12],
  //   starring: ["Harrison Ford", "Karen Allen"],
  //   directors: ["Steven Spielberg"],
  //   poster_path: "assets/posters/14.jpg",
  //   vote_average: 9.1,
  // },
  // {
  //   id: 11,
  //   mediaType: MediaType.Film,
  //   title: "The Shining",
  //   release_date: "1980-1-1",
  //   genres: [27],
  //   starring: ["Jack Nicholson", "Shelley Duvall"],
  //   directors: ["Stanley Kubrick"],
  //   poster_path: "assets/posters/15.jpg",
  //   vote_average: 8.8,
  // },
  // {
  //   id: 12,
  //   mediaType: MediaType.Film,
  //   title: "Gladiator II",
  //   release_date: "2024-10-18",
  //   overview:
  //     "After his home is conquered by the tyrannical emperors who now lead Rome, Lucius is forced to enter the Colosseum and must look to his past to find strength to return the glory of Rome to its people.",
  //   genres: [28, 12, 18],
  //   starring: ["Paul Mescal", "Denzel Washington"],
  //   directors: ["Ridley Scott"],
  //   poster_path: "assets/posters/19.jpg",
  //   vote_average: 7.3,
  // },
  // {
  //   id: 13,
  //   mediaType: MediaType.TV,
  //   title: "The Expanse",
  //   release_date: "2015-1-1",
  //   genres: [10765, 18],
  //   starring: ["John Travolta", "Uma Thurman"],
  //   poster_path: "assets/posters/5.jpg",
  //   vote_average: 8.7,
  // },
  // {
  //   id: 14,
  //   mediaType: MediaType.TV,
  //   title: "South Park",
  //   release_date: "1998-01-01",
  //   genres: [35],
  //   starring: ["Trey Parker ", "Matt Stone", "Isaac Hayes"],
  //   poster_path: "assets/posters/6.jpg",
  //   vote_average: 8.5,
  // },
  // {
  //   id: 15,
  //   mediaType: MediaType.TV,
  //   title: "Severance",
  //   release_date: "2022-01-01",
  //   genres: [10765, 9648],
  //   starring: ["Adam Scott", "Zach Cherry", "Britt Lower"],
  //   poster_path: "assets/posters/7.jpg",
  //   vote_average: 9,
  // },
  // {
  //   id: 16,
  //   mediaType: MediaType.TV,
  //   title: "The Wire",
  //   release_date: "2002-01-01",
  //   genres: [80, 18],
  //   starring: ["Dominic West", "Lance Reddick", "Sonja Sohn"],
  //   poster_path: "assets/posters/8.jpg",
  //   vote_average: 9.6,
  // },
  // {
  //   id: 17,
  //   mediaType: MediaType.TV,
  //   title: "John Adams",
  //   release_date: "2008-01-01",
  //   genres: [18, 10768],
  //   starring: ["Paul Giamatti", "Laura Linney", "John Dossett"],
  //   poster_path: "assets/posters/16.jpg",
  //   vote_average: 9,
  // },
  // {
  //   id: 18,
  //   mediaType: MediaType.TV,
  //   title: "Better Call Saul",
  //   release_date: "2015-01-01",
  //   genres: [80, 18],
  //   starring: ["Bob Odenkirk", "Rhea Seehorn", "Jonathan Banks"],
  //   poster_path: "assets/posters/17.jpg",
  //   vote_average: 9,
  // },
  // {
  //   id: 19,
  //   mediaType: MediaType.TV,
  //   title: "Breaking Bad",
  //   release_date: "2008-01-01",
  //   genres: [80, 18],
  //   starring: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
  //   poster_path: "assets/posters/18.jpg",
  //   vote_average: 9.2,
  // },
  // {
  //   id: 20,
  //   mediaType: MediaType.TV,
  //   title: "Dune: Prophecy",
  //   release_date: "2024-10-31",
  //   genres: [10759, 10765],
  //   starring: ["Emily Watson", "Olivia Williams", "Travis Fimmel"],
  //   poster_path: "assets/posters/20.jpg",
  //   vote_average: 7.6,
  // },
];
