import {LibraryItem} from '../interfaces/library-item.interface';
import {MediaType} from '../enums/media-type.enum';

export const LIBRARY_ITEMS: LibraryItem[] = [
  {
    id: 1,
    mediaType: MediaType.Film,
    title: "Pulp Fiction",
    release_date: new Date(1994, 0, 1),
    genre_ids: [80, 18],
    starring: ["John Travolta", "Uma Thurman"],
    directors: ["Quentin Tarantino"],
    poster_path: "assets/posters/1.jpg",
    vote_average: 9.2,
  },
  {
    id: 2,
    mediaType: MediaType.Film,
    title: "Prisoners",
    release_date: 2013,
    genre_ids: [18, 53],
    starring: ["Hugh Jackman", "Jake Gyllenhaal"],
    directors: ["Denis Villeneuve"],
    poster_path: "assets/posters/2.jpg",
    vote_average: 9.1,
  },
  {
    id: 3,
    mediaType: MediaType.Film,
    title: "The Blues Brothers",
    release_date: 1980,
    genre_ids: [35, 10402],
    starring: ["John Belushi", "Dan Aykroyd"],
    directors: ["John Landis"],
    poster_path: "assets/posters/3.jpg",
    vote_average: 8.8,
  },
  {
    id: 4,
    mediaType: MediaType.Film,
    title: "Inception",
    release_date: 2010,
    genre_ids: [28, 12],
    starring: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
    directors: ["Christopher Nolan"],
    poster_path: "assets/posters/4.jpg",
    vote_average: 9,
  },
  {
    id: 5,
    mediaType: MediaType.Film,
    title: "The Godfather",
    release_date: 1972,
    overview:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    genre_ids: [80, 18],
    starring: ["Marlon Brando", "Al Pacino"],
    directors: ["Francis Ford Coppola"],
    poster_path: "assets/posters/9.jpg",
    vote_average: 9.1,
  },
  {
    id: 6,
    mediaType: MediaType.Film,
    title: "The Matrix",
    release_date: 1999,
    genre_ids: [28, 878],
    starring: ["Keanu Reeves", "Laurence Fishburne"],
    directors: ["Lana Wachowski", "Lilly Wachowski"],
    poster_path: "assets/posters/10.jpg",
    vote_average: 9.2,
  },
  {
    id: 7,
    mediaType: MediaType.Film,
    title: "Dune Part Two",
    release_date: 2024,
    genre_ids: [28, 878],
    starring: ["Timothée Chalamet", "Zendaya"],
    directors: ["Denis Villeneuve"],
    poster_path: "assets/posters/11.jpg",
    vote_average: 9.1,
  },
  {
    id: 8,
    mediaType: MediaType.Film,
    title: "Alien",
    release_date: 1979,
    genre_ids: [878, 27],
    starring: ["Sigourney Weaver", "gourney Weaver"],
    directors: ["Ridley Scott"],
    poster_path: "assets/posters/12.jpg",
    vote_average: 8.8,
  },
  {
    id: 9,
    mediaType: MediaType.Film,
    title: "Memento",
    release_date: 2000,
    genre_ids: [53],
    starring: ["Guy Pearce", "Carrie-Anne Moss"],
    directors: ["Christopher Nolan"],
    poster_path: "assets/posters/13.jpg",
    vote_average: 9.2,
  },
  {
    id: 10,
    mediaType: MediaType.Film,
    title: "Raiders of The Lost Ark",
    release_date: 1981,
    genre_ids: [12],
    starring: ["Harrison Ford", "Karen Allen"],
    directors: ["Steven Spielberg"],
    poster_path: "assets/posters/14.jpg",
    vote_average: 9.1,
  },
  {
    id: 11,
    mediaType: MediaType.Film,
    title: "The Shining",
    release_date: 1980,
    genre_ids: [27],
    starring: ["Jack Nicholson", "Shelley Duvall"],
    directors: ["Stanley Kubrick"],
    poster_path: "assets/posters/15.jpg",
    vote_average: 8.8,
  },
  {
    id: 12,
    mediaType: MediaType.Film,
    title: "Gladiator II",
    release_date: new Date(2024, 9, 18),
    overview:
      "After his home is conquered by the tyrannical emperors who now lead Rome, Lucius is forced to enter the Colosseum and must look to his past to find strength to return the glory of Rome to its people.",
    genre_ids: [28, 12, 18],
    starring: ["Paul Mescal", "Denzel Washington"],
    directors: ["Ridley Scott"],
    poster_path: "assets/posters/19.jpg",
    vote_average: 7.3,
  },
  {
    id: 13,
    mediaType: MediaType.TV,
    title: "The Expanse",
    release_date: 2015,
    genre_ids: [10765, 18],
    starring: ["John Travolta", "Uma Thurman"],
    creators: ["Daniel Abraham", "Mark Fergus", "Ty Franck"],
    poster_path: "assets/posters/5.jpg",
    vote_average: 8.7,
  },
  {
    id: 14,
    mediaType: MediaType.TV,
    title: "South Park",
    release_date: 1998,
    genre_ids: [35],
    starring: ["Trey Parker ", "Matt Stone", "Isaac Hayes"],
    creators: ["Trey Parker ", "Matt Stone"],
    poster_path: "assets/posters/6.jpg",
    vote_average: 8.5,
  },
  {
    id: 15,
    mediaType: MediaType.TV,
    title: "Severance",
    release_date: 2022,
    genre_ids: [10765, 9648],
    starring: ["Adam Scott", "Zach Cherry", "Britt Lower"],
    creators: ["Dan Erickson"],
    poster_path: "assets/posters/7.jpg",
    vote_average: 9,
  },
  {
    id: 16,
    mediaType: MediaType.TV,
    title: "The Wire",
    release_date: 2002,
    genre_ids: [80, 18],
    starring: ["Dominic West", "Lance Reddick", "Sonja Sohn"],
    creators: ["David Simon"],
    poster_path: "assets/posters/8.jpg",
    vote_average: 9.6,
  },
  {
    id: 17,
    mediaType: MediaType.TV,
    title: "John Adams",
    release_date: 2008,
    genre_ids: [18, 10768],
    starring: ["Paul Giamatti", "Laura Linney", "John Dossett"],
    creators: ["Tom Hooper"],
    poster_path: "assets/posters/16.jpg",
    vote_average: 9,
  },
  {
    id: 18,
    mediaType: MediaType.TV,
    title: "Better Call Saul",
    release_date: 2015,
    genre_ids: [80, 18],
    starring: ["Bob Odenkirk", "Rhea Seehorn", "Jonathan Banks"],
    creators: ["Vince Gilligan", "Peter Gould"],
    poster_path: "assets/posters/17.jpg",
    vote_average: 9,
  },
  {
    id: 19,
    mediaType: MediaType.TV,
    title: "Breaking Bad",
    release_date: 2008,
    genre_ids: [80, 18],
    starring: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
    creators: ["Vince Gilligan"],
    poster_path: "assets/posters/18.jpg",
    vote_average: 9.2,
  },
  {
    id: 20,
    mediaType: MediaType.TV,
    title: "Dune: Prophecy",
    release_date: new Date(2024, 9, 31),
    genre_ids: [10759, 10765],
    starring: ["Emily Watson", "Olivia Williams", "Travis Fimmel"],
    creators: ["Dianne Ademu-John", "Alison Schapker"],
    poster_path: "assets/posters/20.jpg",
    vote_average: 7.6,
  },
];
