export const FilmGenres: Record<string, number> = {
  [$localize`:@@film-genre.action:Action`]: 28,
  [$localize`:@@film-genre.adventure:Adventure`]: 12,
  [$localize`:@@film-genre.animation:Animation`]: 16,
  [$localize`:@@film-genre.comedy:Comedy`]: 35,
  [$localize`:@@film-genre.crime:Crime`]: 80,
  [$localize`:@@film-genre.documentary:Documentary`]: 99,
  [$localize`:@@film-genre.drama:Drama`]: 18,
  [$localize`:@@film-genre.family:Family`]: 10751,
  [$localize`:@@film-genre.fantasy:Fantasy`]: 14,
  [$localize`:@@film-genre.history:History`]: 36,
  [$localize`:@@film-genre.horror:Horror`]: 27,
  [$localize`:@@film-genre.music:Music`]: 10402,
  [$localize`:@@film-genre.mystery:Mystery`]: 9648,
  [$localize`:@@film-genre.romance:Romance`]: 10749,
  [$localize`:@@film-genre.scienceFiction:Science Fiction`]: 878,
  [$localize`:@@film-genre.tvMovie:TV Movie`]: 10770,
  [$localize`:@@film-genre.thriller:Thriller`]: 53,
  [$localize`:@@film-genre.war:War`]: 10752,
  [$localize`:@@film-genre.western:Western`]: 37,
};
