export const TvGenres: Record<string, number> = {
  [$localize`:@@tv-genre.actionAdventure:Action & Adventure`]: 10759,
  [$localize`:@@tv-genre.animation:Animation`]: 16,
  [$localize`:@@tv-genre.comedy:Comedy`]: 35,
  [$localize`:@@tv-genre.crime:Crime`]: 80,
  [$localize`:@@tv-genre.documentary:Documentary`]: 99,
  [$localize`:@@tv-genre.drama:Drama`]: 18,
  [$localize`:@@tv-genre.family:Family`]: 10751,
  [$localize`:@@tv-genre.kids:Kids`]: 10762,
  [$localize`:@@tv-genre.mystery:Mystery`]: 9648,
  [$localize`:@@tv-genre.news:News`]: 10763,
  [$localize`:@@tv-genre.reality:Reality`]: 10764,
  [$localize`:@@tv-genre.sciFiFantasy:Sci-Fi & Fantasy`]: 10765,
  [$localize`:@@tv-genre.soap:Soap`]: 10766,
  [$localize`:@@tv-genre.talk:Talk`]: 10767,
  [$localize`:@@tv-genre.warPolitics:War & Politics`]: 10768,
  [$localize`:@@tv-genre.western:Western`]: 37,
};
